spring:
  profiles:
    active: default
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/zeph}
    username: ${DB_USERNAME:sangrae}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:false}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  api:
    key: ${KAKAO_API_KEY}


ai:
  server:
    url: ${AI_SERVER_URL:http://localhost:8000}

server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: ${SERVER_FORWARD_HEADERS_STRATEGY:framework}

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

logging:
  level:
    org.springframework.security: DEBUG
