spring:
  profiles:
    active: default
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/zeph
    username: sangrae
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 9d06b1510ebadbaf0cb4e6349589b03e
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

kakao:
  api:
    key: ${KAKAO_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger
    groups-order: DESC
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**

logging:
  level:
    org.springframework.security: DEBUG
